export const userConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  LOGOUT: "USERS_LOGOUT",
  UPDATE_FOLLOWERS: "UPDATE_FOLLOWERS",
  SEARCH: "SEARCH"
};
export const loaderConstants = {
  LOADING_INFO: "LOADING",
  POPUP_MODAL_INFO: "POPUP_MODAL"
};
